export const JWT_PUBLIC_KEY =
  process.env.JWT_PUBLIC_KEY ||
  `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqiioZzwBmHtLVRv3LAal
t/Henj66rLEijOLcW1LBEU0ShO5PzsBJVqRSvlRsgKIdY9JiV6aAJrVItBAs2js9
xwfunfWNp3qzjWjMRAEx3LOQ9vMfbjhs455EljbGcVHuEnoLdC1kM6wYXh4gzm7s
qaKfy7l9YSDW4Et4RTt6tWcq/p0J+bwMffU9z5wyOJYkxtRrMKOwhOmb7ClmVxPx
LaEuG2E1aeaQcGhhJf/Ali3RF9tBmDk1YEj1uPFmPFRkR3HT2g1Clb3HKcZ/Dzns
ebbPhvnJ4HocSNaG40I1NRA6PHctTgWwv4rCVCvMIq4IIQLBOJCqaWzkUwd54vGJ
xwIDAQAB
-----END PUBLIC KEY-----
`;
